# Generated by Django 5.2.9 on 2026-01-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('sales_type', models.CharField(choices=[('DIRECT', 'Direct Sale Only'), ('AUCTION', 'Auction Only'), ('HYBRID', 'Hybrid (Auction + Buy Now)')], default='DIRECT', max_length=20)),
                ('initial_price', models.DecimalField(decimal_places=2, help_text='Starting price for direct sale or auction start', max_digits=10)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_highest_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reserve_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum price to sell in auction', max_digits=10)),
                ('auction_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
