# Generated by Django 5.2.9 on 2026-01-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Payment')], default='ACTIVE', max_length=20),
        ),
    ]
