# Generated by Django 5.2.9 on 2026-01-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_variable_price',
            field=models.BooleanField(default=False, help_text='If true, price defaults to 0 and user selects amount.'),
        ),
    ]
